#!/usr/bin/env python3
"""Convert pbrt-v4's Hosek spectral data header to Rust constants.

The generated file is checked in and is not regenerated during a normal crate
build.  Paths are deliberately relative to the pbrt-r4 repository root.
"""

from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path


ARRAY_RE = re.compile(
    r"double\s+(dataset(?:Rad)?\d+|solarDataset\d+|limbDarkeningDataset\d+)\[\]\s*=\s*\{(.*?)\};",
    re.DOTALL,
)
NUMBER_RE = re.compile(r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?")


def parse_arrays(source: str) -> dict[str, list[str]]:
    arrays: dict[str, list[str]] = {}
    for match in ARRAY_RE.finditer(source):
        name, body = match.groups()
        body = re.sub(r"/\*.*?\*/|//[^\n]*", "", body, flags=re.DOTALL)
        values = NUMBER_RE.findall(body)
        if name in arrays:
            raise ValueError(f"duplicate array: {name}")
        arrays[name] = values
    return arrays


def ordered(arrays: dict[str, list[str]], prefix: str) -> list[tuple[str, list[str]]]:
    result = sorted(
        (
            (name, values)
            for name, values in arrays.items()
            if name.startswith(prefix)
            and not (prefix == "dataset" and name.startswith("datasetRad"))
        ),
        key=lambda item: int(re.search(r"\d+$", item[0]).group()),
    )
    expected = list(range(320, 721, 40))
    actual = [int(re.search(r"\d+$", name).group()) for name, _ in result]
    if actual != expected:
        raise ValueError(f"{prefix}: expected wavelengths {expected}, got {actual}")
    return result


def rust_array(values: list[str]) -> str:
    values = [value if "." in value or "e" in value.lower() else f"{value}.0" for value in values]
    lines = []
    for index in range(0, len(values), 6):
        lines.append("    " + ", ".join(values[index : index + 6]) + ",")
    return "\n".join(lines)


def render_group(name: str, arrays: list[tuple[str, list[str]]]) -> str:
    item_lines = []
    for array_name, values in arrays:
        item_lines.append(f"pub static {array_name.upper()}: &[f64] = &[\n{rust_array(values)}\n];")
    names = ",\n    ".join(f"{array_name.upper()}" for array_name, _ in arrays)
    item_lines.append(f"pub static {name}: &[&[f64]] = &[\n    {names}\n];")
    return "\n\n".join(item_lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("../pbrt-v4/src/ext/skymodel/ArHosekSkyModelData_Spectral.h"),
    )
    parser.add_argument(
        "--output", type=Path, default=Path("src/ext/skymodel/data.rs")
    )
    args = parser.parse_args()

    source_bytes = args.input.read_bytes()
    arrays = parse_arrays(source_bytes.decode())
    datasets = ordered(arrays, "dataset")
    radiance_datasets = ordered(arrays, "datasetRad")
    solar_datasets = ordered(arrays, "solarDataset")
    limb = ordered(arrays, "limbDarkeningDataset")

    if any(len(values) != 1080 for _, values in datasets):
        raise ValueError("spectral coefficient array must contain 1080 values")
    if any(len(values) != 120 for _, values in radiance_datasets):
        raise ValueError("spectral radiance array must contain 120 values")
    if any(len(values) != 1800 for _, values in solar_datasets):
        raise ValueError("solar radiance array must contain 1800 values")
    if any(len(values) != 6 for _, values in limb):
        raise ValueError("limb-darkening array must contain 6 values")

    source_sha256 = hashlib.sha256(source_bytes).hexdigest()
    output = f"""// Generated by tools/extract_hosek_spectral_data.py.
// Source: pbrt-v4/src/ext/skymodel/ArHosekSkyModelData_Spectral.h.
// Source data version: Hosek-Wilkie 1.4a, February 22nd, 2013.
// Source SHA-256: {source_sha256}
// The source data is distributed under the 3-clause BSD license by
// Lukas Hosek and Alexander Wilkie; retain the accompanying license notice.

pub const SPECTRAL_WAVELENGTHS: [f64; 11] =
    [320.0, 360.0, 400.0, 440.0, 480.0, 520.0, 560.0, 600.0, 640.0, 680.0, 720.0];

"""
    output += render_group("DATASETS", datasets)
    output += "\n\n"
    output += render_group("RADIANCE_DATASETS", radiance_datasets)
    output += "\n\n"
    output += render_group("SOLAR_DATASETS", solar_datasets)
    output += "\n\n"
    output += render_group("LIMB_DARKENING_DATASETS", limb)
    output += "\n"

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output)


if __name__ == "__main__":
    main()
